const data = [
  {
    _id: '60908cb30812033def2e7433',
    index: 0,
    guid: '818f9a7e-82f0-4816-af73-4b59b27d3cc3',
    isActive: false,
    balance: '$1,642.86',
    picture: 'http://placehold.it/32x32',
    age: 30,
    eyeColor: 'blue',
    name: 'Lopez Pate',
    gender: 'male',
    company: 'NITRACYR',
    email: 'lopezpate@nitracyr.com',
    phone: '+1 (959) 558-2398',
    address: '259 Tapscott Street, Marbury, Virgin Islands, 8499',
    about:
      'Commodo nostrud dolor aliquip minim nulla deserunt esse exercitation aliqua dolor irure occaecat eiusmod irure. Dolore deserunt dolore id est. Sunt ea dolore ullamco fugiat ex nulla ad commodo consectetur irure laboris fugiat laborum. Incididunt veniam irure sunt tempor aliqua reprehenderit nulla anim reprehenderit.\r\n',
    registered: '2019-04-20T10:49:50 +03:00',
    latitude: 20.301768,
    longitude: 15.555296,
    tags: ['pariatur', 'non', 'est', 'cupidatat', 'sint', 'incididunt', 'ex'],
    friends: [
      {
        id: 0,
        name: 'Ramos Gray',
      },
      {
        id: 1,
        name: 'Charlotte Caldwell',
      },
      {
        id: 2,
        name: 'Margie Price',
      },
    ],
    greeting: 'Hello, Lopez Pate! You have 9 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '60908cb3c4e1b2cc1a6c30ee',
    index: 1,
    guid: 'aa9a9a72-e58f-49c2-8a06-4bcfa62a20d8',
    isActive: true,
    balance: '$2,468.17',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Cox Bruce',
    gender: 'male',
    company: 'CENTURIA',
    email: 'coxbruce@centuria.com',
    phone: '+1 (935) 600-2792',
    address: '383 Gain Court, Floriston, Missouri, 4783',
    about:
      'Eiusmod et eiusmod eiusmod ex est reprehenderit do do dolore laboris excepteur. In proident deserunt elit culpa et nisi. Ex cupidatat consectetur velit Lorem ipsum fugiat nisi id dolor deserunt.\r\n',
    registered: '2021-04-10T01:43:40 +03:00',
    latitude: -5.631572,
    longitude: -105.072954,
    tags: [
      'consequat',
      'nulla',
      'est',
      'exercitation',
      'tempor',
      'eiusmod',
      'est',
    ],
    friends: [
      {
        id: 0,
        name: 'Jefferson Vaughn',
      },
      {
        id: 1,
        name: 'Antoinette Hernandez',
      },
      {
        id: 2,
        name: 'Peterson Marks',
      },
    ],
    greeting: 'Hello, Cox Bruce! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '60908cb36610ab57ec0a0bff',
    index: 2,
    guid: '7b80e912-0dd5-44c4-a7d5-decd0eeaffda',
    isActive: false,
    balance: '$3,439.25',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'blue',
    name: 'Krista Wilcox',
    gender: 'female',
    company: 'ZILIDIUM',
    email: 'kristawilcox@zilidium.com',
    phone: '+1 (980) 488-3877',
    address: '644 Windsor Place, Walland, Virginia, 8962',
    about:
      'Culpa excepteur aliqua aute occaecat laborum ad proident cillum. Aute laboris voluptate ad qui veniam sunt sit veniam consectetur quis. Laborum ea aliqua mollit dolor nostrud.\r\n',
    registered: '2017-04-01T03:32:02 +03:00',
    latitude: -34.998418,
    longitude: -126.892773,
    tags: ['do', 'enim', 'quis', 'sit', 'magna', 'minim', 'tempor'],
    friends: [
      {
        id: 0,
        name: 'Melba Barnes',
      },
      {
        id: 1,
        name: 'Claudette Burnett',
      },
      {
        id: 2,
        name: 'Bruce Brooks',
      },
    ],
    greeting: 'Hello, Krista Wilcox! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '60908cb37a43727714cddb74',
    index: 3,
    guid: '5ddd3d71-d77f-4fa0-aa88-8007ef2d6ba2',
    isActive: false,
    balance: '$1,249.24',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'green',
    name: 'Francis Green',
    gender: 'female',
    company: 'PHARMACON',
    email: 'francisgreen@pharmacon.com',
    phone: '+1 (997) 545-3975',
    address: '385 Jewel Street, Gulf, Marshall Islands, 1777',
    about:
      'Quis cillum sunt enim dolore eu laborum. Ut incididunt deserunt esse do in nostrud fugiat qui amet deserunt magna est. Commodo elit eiusmod labore commodo laborum nulla eu sit est cupidatat et quis. Reprehenderit magna mollit deserunt id excepteur irure consectetur cupidatat fugiat veniam veniam. Incididunt proident occaecat minim quis id anim ut velit. Culpa exercitation ipsum duis mollit ea.\r\n',
    registered: '2014-10-07T02:47:19 +03:00',
    latitude: -16.004737,
    longitude: 38.502699,
    tags: [
      'dolore',
      'reprehenderit',
      'sunt',
      'sit',
      'reprehenderit',
      'occaecat',
      'proident',
    ],
    friends: [
      {
        id: 0,
        name: 'Lizzie Roth',
      },
      {
        id: 1,
        name: 'Juliana Salinas',
      },
      {
        id: 2,
        name: 'Bethany Jennings',
      },
    ],
    greeting: 'Hello, Francis Green! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '60908cb3dae14486830bd434',
    index: 4,
    guid: '9cc37ebe-0db8-490d-bb8c-8b080df9374c',
    isActive: true,
    balance: '$1,147.60',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'brown',
    name: 'Valeria Duran',
    gender: 'female',
    company: 'ZIGGLES',
    email: 'valeriaduran@ziggles.com',
    phone: '+1 (956) 517-2948',
    address: '546 Milton Street, Blue, Oregon, 3901',
    about:
      'Magna dolore id mollit nisi amet ut duis ex. Incididunt consequat eiusmod non aute Lorem Lorem cillum ex aute. Exercitation nostrud laborum in labore labore voluptate.\r\n',
    registered: '2015-03-22T12:18:48 +03:00',
    latitude: -32.35846,
    longitude: -109.796708,
    tags: [
      'aute',
      'exercitation',
      'voluptate',
      'labore',
      'est',
      'elit',
      'excepteur',
    ],
    friends: [
      {
        id: 0,
        name: 'Jillian Cox',
      },
      {
        id: 1,
        name: 'Teri Murphy',
      },
      {
        id: 2,
        name: 'Bauer Sims',
      },
    ],
    greeting: 'Hello, Valeria Duran! You have 9 unread messages.',
    favoriteFruit: 'banana',
  },
];

export default data;
